### PR TITLE
Do not strip newlines from post content

### PR DESCRIPTION
**Pull request by pathawks**
Since posts may contain code blocks, or some other content with pre-formatted whitespace, we *do not* want to strip whitespace from post content.

This pull request strips whitespace from the template *before* it is rendered, rather than after. This will keep all the whitespace from the post content intact.

### CODE REVIEW

**Comment by parkr** [comment]
Example? We should add a test for this.

**Comment by pathawks** [comment]
Test has been added

**Comment by benbalter** [comment]
Nice. Thanks for adding the test @pathawks (and for all the contributions!)

**Comment by pathawks** [comment]
> Thanks for adding the test @pathawks (and for all the contributions!)

Thank you @benbalter; I've been waiting for a plugin like this for a while! :beers:

**Pull request merged**
